### ISSUE TITLE
Output file should be named by device we evaluate or firmware vesion

### ISSUE THREAD

**Issue by pietrushnic** [3mdeb/fwdump-docker#6]
Name `fwlogs.tar.gz` is not sufficient and can be easily confused. While getting logs we gaining enough information to uniquely call the dump.

**Comment by miczyg1** [comment]
The filename is now composed from <board_manufacturer>_<board_model><firmware_version>.tar.gz: https://github.com/3mdeb/fwdump-docker/pull/7
